version: '3.6'

services:
  postgres:
    image: postgres
    restart: always
    container_name: 'database'
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: "${PG_PASSWORD}"
      POSTGRES_USER: "${PG_USER}"
